#!/bin/bash

DATE=$(date +"%Y-%m-%d_%H_%M")
format=$(echo ${DATE:11:2}:${DATE:14:2} ${DATE:8:2}/${DATE:5:2}/${DATE:0:4})

#raspistill --annotate "$format" -w 1280 -h 720 -q 100 -o /var/www/html/camera/$DATE.jpg
raspistill -w 1280 -h 720 -q 100 -o /var/www/html/camera/$DATE.jpg
